version: "3"
services:
  app:
    build: .
    ports:
      - "4000:80"
    env_file: .env
    depends_on:
      - ravendb
    volumes:
      - ./:/app
  ravendb:
    image: ravendb/ravendb:4.0.3-patch-40033-ubuntu.16.04-x64
    env_file: .ravenenv
    ports:
      - "8080:8080"
      - "38888:38888"